services:
  service-php:
    container_name: service-php
    build:
      context: .
      dockerfile: ./.docker/docker-fpm/Dockerfile
    volumes:
    - ./src:/var/www/html
    depends_on:
    - service-mysql
    - service-redis
    networks:
    - ${DOCKER_NETWORK}
    command: sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"


  service-apache:
    container_name: service-apache
    build:
      context: .
      dockerfile: ./.docker/docker-apache/Dockerfile
    ports:
    - "${DOCKER_PHP_PORT}:80"
    volumes:
    - ./src:/var/www/html:ro
    - ./.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
    depends_on:
    - service-php
    networks:
    - ${DOCKER_NETWORK}

  service-composer:
    container_name: service-composer
    build:
      context: .
      dockerfile: ./.docker/docker-composer/Dockerfile
    volumes:
    - ./src:/var/www/html
    networks:
    - ${DOCKER_NETWORK}

  service-mysql:
    container_name: service-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    ports:
    - "${DOCKER_MYSQL_PORT}:3306"
    volumes:
    - ./.docker/volumes/mysql-data:/var/lib/mysql
    networks:
    - ${DOCKER_NETWORK}

  service-redis:
    image: redis:latest
    container_name: service-redis
    ports:
    - "${DOCKER_REDIS_PORT}:6379"
    networks:
    - ${DOCKER_NETWORK}

  service-phpmyadmin:
    container_name: service-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: service-mysql
    ports:
    - "${DOCKER_PHPMYADMIN_PORT}:80"
    networks:
    - ${DOCKER_NETWORK}

  service-mailpit:
    container_name: service-mailpit
    image: axllent/mailpit:latest
    ports:
    - "${DOCKER_MAILPIT_PORT}:8025"
    - "1025:1025"
    networks:
    - ${DOCKER_NETWORK}


networks:
  red-app:
    driver: bridge

volumes:
  mysql-data: